// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOpUZ_SufrVAGH-MsLreDsj53nSQB4kM',
    appId: '1:874628167347:web:3db4243273f75df0fb62c6',
    messagingSenderId: '874628167347',
    projectId: 'aromablend-fd363',
    authDomain: 'aromablend-fd363.firebaseapp.com',
    storageBucket: 'aromablend-fd363.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvsTb66dtCorYZv2-TxLU6OJK7vwpUlA',
    appId: '1:874628167347:android:73fe5c6da80454c8fb62c6',
    messagingSenderId: '874628167347',
    projectId: 'aromablend-fd363',
    storageBucket: 'aromablend-fd363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1yBE4HcXj7dynhHOUSJ-e90mc5uYMJns',
    appId: '1:874628167347:ios:b7cb371052becaa1fb62c6',
    messagingSenderId: '874628167347',
    projectId: 'aromablend-fd363',
    storageBucket: 'aromablend-fd363.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1yBE4HcXj7dynhHOUSJ-e90mc5uYMJns',
    appId: '1:874628167347:ios:3f946ec2cc9c7922fb62c6',
    messagingSenderId: '874628167347',
    projectId: 'aromablend-fd363',
    storageBucket: 'aromablend-fd363.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
